# JVM Memory Allocation
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.daemon=true

# AndroidX & Tooling Flags
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

# Kotlin Configuration
kotlin.code.style=official
kotlin.incremental=true




